/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.disperindag.panel;

import com.disperindag.Util.txtNumber_validator;
import com.disperindag.dao.daoData_Legalitas;
import com.disperindag.dialog.JDialog_Izin;
import com.disperindag.model.Data_legalitas;
import com.disperindag.sql.PERUSAHAAN;
import com.disperindag.tableModel.TabelModel_izin;
import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.border.TitledBorder;

/**
 *
 * @author TOSHIBA
 */
public class Panel_Legalitas extends javax.swing.JPanel {

    final static Font fontBorder = new Font("arial", Font.BOLD, 12);
    final static String dateFormat = "dd-MM-yyyy";
    private Connection con = null;
    private TabelModel_izin ti = null;
    private daoData_Legalitas dl = null;
    private JDialog_Izin ji = null;
    private int _id;

    /**
     * Creates new form Panel_Legalitas_perush
     */
    public Panel_Legalitas(Connection con, String jenisPT, boolean edit) {
        initComponents();
        this.con = con;
        dl = new daoData_Legalitas(con);
        cekPanel(jenisPT, edit);
        clear();
    }

    public void setId(int id) {
        this._id = id;
        ti = new TabelModel_izin(id);
        Tabel_izin.setModel(ti);
    }

    public void setLegalitas(Data_legalitas l) {
        try {
            txt_noBerdiri.setText(l.getNo_akta_berdiri());
            Date_akta_berdiri.setDate(l.getTgl_akta_berdiri());
            txt_notaris1.setText(l.getNama_notaris_berdiri());
            txt_alamat.setText(l.getAlamat());
            txt_notlp.setText(l.getNotlp());
            txt_noPerubahan1.setText(l.getNo_akta_perubahan1());
            Date_akta_perubahan1.setDate(l.getTgl_akta_perubahan1());
            txt_notaris2.setText(l.getNama_notaris_perubahan());
            txt_noPerubahan2.setText(l.getNo_akta_perubahan2());
            Date_akta_perubahan2.setDate(l.getTgl_akta_perubahan2());
            txt_noPersetujuan.setText(l.getNo_perse7());
            Date_persetujuan.setDate(l.getTgl_perse7());
            txt_noPengesahan.setText(l.getNo_pengesahan());
            Date_pengesahan.setDate(l.getTglPengesahan());
            txt_noLaporan.setText(l.getNo_laporan());
            Date_laporan.setDate(l.getTglLaporan());
            txt_noPemberitahuan.setText(l.getNo_pemberitahuan());
            Date_Pemberitahuan.setDate(l.getTglPemberitahuan());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void SimpanData() {
        try {
            Data_legalitas l = new Data_legalitas();
            l.setId_legalitas(_id);
            l.setNo_akta_berdiri(txt_noBerdiri.getText());
            l.setTgl_akta_berdiri(Date_akta_berdiri.getDate());
            l.setNama_notaris_berdiri(txt_notaris1.getText());
            l.setAlamat(txt_alamat.getText());
            l.setNotlp(txt_notlp.getText());
            l.setNo_akta_perubahan1(txt_noPerubahan1.getText());
            l.setTgl_akta_perubahan1(Date_akta_perubahan1.getDate());
            l.setNama_notaris_perubahan(txt_notaris2.getText());
            l.setNo_akta_perubahan2(txt_noPerubahan2.getText());
            l.setTgl_akta_perubahan2(Date_akta_perubahan2.getDate());
            l.setNo_perse7(txt_noPersetujuan.getText());
            l.setTgl_perse7(Date_persetujuan.getDate());
            l.setNo_pengesahan(txt_noPengesahan.getText());
            l.setTglPengesahan(Date_pengesahan.getDate());
            l.setNo_laporan(txt_noLaporan.getText());
            l.setTglLaporan(Date_laporan.getDate());
            l.setNo_pemberitahuan(txt_noPemberitahuan.getText());
            l.setTglPemberitahuan(Date_Pemberitahuan.getDate());

            if (dl.updateLegalitas(l) == true) {
                clear();
                JOptionPane.showMessageDialog(this, "Data tersimpan");
            }
        } catch (SQLException | HeadlessException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        pnl_pendirian = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_noBerdiri = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_notaris1 = new javax.swing.JTextField();
        Date_akta_berdiri = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_alamat = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txt_notlp = new javax.swing.JTextField();
        pnl_akta_perubahan = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_noPerubahan1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_notaris2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_noPerubahan2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Date_akta_perubahan1 = new com.toedter.calendar.JDateChooser();
        Date_akta_perubahan2 = new com.toedter.calendar.JDateChooser();
        pnl_persetujuan = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_noPersetujuan = new javax.swing.JTextField();
        Date_persetujuan = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabel_izin = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btn_tambah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_simpan = new com.disperindag.widget.Button();
        btn_cancel = new com.disperindag.widget.Button();
        pnl_pengesahan = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_noPengesahan = new javax.swing.JTextField();
        Date_pengesahan = new com.toedter.calendar.JDateChooser();
        pnl_laporan = new javax.swing.JPanel();
        txt_noLaporan = new javax.swing.JTextField();
        Date_laporan = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pnl_pemberitahuan = new javax.swing.JPanel();
        txt_noPemberitahuan = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Date_Pemberitahuan = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();

        pnl_pendirian.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "AKTA PENDIRIAN", 0, 0, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jLabel1.setText("Nomor");

        jLabel2.setText("Tanggal Pengesahan");

        jLabel3.setText("Nama Notaris");

        Date_akta_berdiri.setDateFormatString("dd - MMM - yyyy");

        jLabel4.setText("Alamat ");

        txt_alamat.setColumns(20);
        txt_alamat.setRows(5);
        jScrollPane1.setViewportView(txt_alamat);

        jLabel5.setText("No tlp");

        javax.swing.GroupLayout pnl_pendirianLayout = new javax.swing.GroupLayout(pnl_pendirian);
        pnl_pendirian.setLayout(pnl_pendirianLayout);
        pnl_pendirianLayout.setHorizontalGroup(
            pnl_pendirianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_pendirianLayout.createSequentialGroup()
                .addGroup(pnl_pendirianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_pendirianLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel1))
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(pnl_pendirianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_notaris1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_pendirianLayout.createSequentialGroup()
                        .addComponent(txt_noBerdiri, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Date_akta_berdiri, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(txt_notlp))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pnl_pendirianLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel3});

        pnl_pendirianLayout.setVerticalGroup(
            pnl_pendirianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_pendirianLayout.createSequentialGroup()
                .addGroup(pnl_pendirianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_pendirianLayout.createSequentialGroup()
                        .addGroup(pnl_pendirianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_pendirianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_noBerdiri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addComponent(Date_akta_berdiri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_pendirianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_notaris1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_pendirianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnl_pendirianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_pendirianLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(28, 28, 28))
                    .addGroup(pnl_pendirianLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_notlp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pnl_akta_perubahan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Akta Perubahan Terakhir", 0, 0, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jLabel6.setText("Nomor");

        jLabel7.setText("Tanggal Pengesahan");

        jLabel8.setText("Nama Notaris");

        jLabel9.setText("Tanggal Pengesahan");

        jLabel10.setText("Nomor");

        Date_akta_perubahan1.setDateFormatString("dd - MMM - yyyy");

        Date_akta_perubahan2.setDateFormatString("dd - MMM - yyyy");

        javax.swing.GroupLayout pnl_akta_perubahanLayout = new javax.swing.GroupLayout(pnl_akta_perubahan);
        pnl_akta_perubahan.setLayout(pnl_akta_perubahanLayout);
        pnl_akta_perubahanLayout.setHorizontalGroup(
            pnl_akta_perubahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_akta_perubahanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_akta_perubahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(pnl_akta_perubahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl_akta_perubahanLayout.createSequentialGroup()
                        .addComponent(txt_noPerubahan2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Date_akta_perubahan2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnl_akta_perubahanLayout.createSequentialGroup()
                        .addComponent(txt_noPerubahan1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Date_akta_perubahan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txt_notaris2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_akta_perubahanLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel6, jLabel8});

        pnl_akta_perubahanLayout.setVerticalGroup(
            pnl_akta_perubahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_akta_perubahanLayout.createSequentialGroup()
                .addGroup(pnl_akta_perubahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_akta_perubahanLayout.createSequentialGroup()
                        .addGroup(pnl_akta_perubahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_akta_perubahanLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6))
                            .addComponent(Date_akta_perubahan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_akta_perubahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_notaris2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl_akta_perubahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_noPerubahan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_akta_perubahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_akta_perubahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txt_noPerubahan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addComponent(Date_akta_perubahan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        pnl_persetujuan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Persetujuan Menteri Koperasi dan UKM Atas Akta Perubahan Anggaran Dasar", 0, 0, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jLabel16.setText("Nomor");

        jLabel17.setText("Tanggal Pengesahan");

        Date_persetujuan.setDateFormatString("dd - MMM - yyyy");

        javax.swing.GroupLayout pnl_persetujuanLayout = new javax.swing.GroupLayout(pnl_persetujuan);
        pnl_persetujuan.setLayout(pnl_persetujuanLayout);
        pnl_persetujuanLayout.setHorizontalGroup(
            pnl_persetujuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_persetujuanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_persetujuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl_persetujuanLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_noPersetujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_persetujuanLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Date_persetujuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_persetujuanLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel16, jLabel17});

        pnl_persetujuanLayout.setVerticalGroup(
            pnl_persetujuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_persetujuanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_persetujuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txt_noPersetujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_persetujuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(Date_persetujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Izin - Izin Dan Legalitas", 0, 0, new java.awt.Font("Arial", 1, 12))); // NOI18N

        Tabel_izin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Jenis Izin", "Nomor", "Dikeluarkan Oleh", "Tanggal Berlaku", "Masa laku (th)"
            }
        ));
        jScrollPane2.setViewportView(Tabel_izin);

        jPanel5.setLayout(new java.awt.GridLayout(3, 1, 10, 5));

        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        jPanel5.add(btn_tambah);

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        jPanel5.add(btn_hapus);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_simpan.setText("SIMPAN");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_cancel.setText("BERSIHKAN");

        pnl_pengesahan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pengesahan Menteri Hukum dan HAM", 0, 0, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jLabel11.setText("Nomor");

        jLabel12.setText("Tanggal Pengesahan");

        txt_noPengesahan.setText("jTextField1");

        Date_pengesahan.setDateFormatString("dd - MMM - yyyy");

        javax.swing.GroupLayout pnl_pengesahanLayout = new javax.swing.GroupLayout(pnl_pengesahan);
        pnl_pengesahan.setLayout(pnl_pengesahanLayout);
        pnl_pengesahanLayout.setHorizontalGroup(
            pnl_pengesahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_pengesahanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_pengesahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_pengesahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_noPengesahan)
                    .addComponent(Date_pengesahan, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_pengesahanLayout.setVerticalGroup(
            pnl_pengesahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_pengesahanLayout.createSequentialGroup()
                .addGroup(pnl_pengesahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_pengesahanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11))
                    .addComponent(txt_noPengesahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_pengesahanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(Date_pengesahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_laporan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Penerimaan Laporan Perubahan Anggaran Dasar", 0, 0, new java.awt.Font("Arial", 1, 12))); // NOI18N

        txt_noLaporan.setText("jTextField1");

        Date_laporan.setDateFormatString("dd - MMM - yyyy");

        jLabel13.setText("Nomor");

        jLabel14.setText("Tanggal Pengesahan");

        javax.swing.GroupLayout pnl_laporanLayout = new javax.swing.GroupLayout(pnl_laporan);
        pnl_laporan.setLayout(pnl_laporanLayout);
        pnl_laporanLayout.setHorizontalGroup(
            pnl_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_laporanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_noLaporan)
                    .addComponent(Date_laporan, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_laporanLayout.setVerticalGroup(
            pnl_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_laporanLayout.createSequentialGroup()
                .addGroup(pnl_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_laporanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13))
                    .addComponent(txt_noLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(Date_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_pemberitahuan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Penerimaan Pemberitahuan Perubahan Direksi / Komisaris", 0, 0, new java.awt.Font("Arial", 1, 12))); // NOI18N

        txt_noPemberitahuan.setText("jTextField1");

        jLabel15.setText("Nomor");

        Date_Pemberitahuan.setDateFormatString("dd - MMM - yyyy");

        jLabel18.setText("Tanggal Pengesahan");

        javax.swing.GroupLayout pnl_pemberitahuanLayout = new javax.swing.GroupLayout(pnl_pemberitahuan);
        pnl_pemberitahuan.setLayout(pnl_pemberitahuanLayout);
        pnl_pemberitahuanLayout.setHorizontalGroup(
            pnl_pemberitahuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_pemberitahuanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_pemberitahuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_pemberitahuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_noPemberitahuan)
                    .addComponent(Date_Pemberitahuan, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_pemberitahuanLayout.setVerticalGroup(
            pnl_pemberitahuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_pemberitahuanLayout.createSequentialGroup()
                .addGroup(pnl_pemberitahuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_pemberitahuanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15))
                    .addComponent(txt_noPemberitahuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_pemberitahuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(Date_Pemberitahuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnl_akta_perubahan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_persetujuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_pengesahan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_laporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_pemberitahuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(containerLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnl_pendirian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(39, Short.MAX_VALUE)))
        );

        containerLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel3, pnl_akta_perubahan, pnl_pendirian, pnl_persetujuan});

        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(pnl_akta_perubahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_persetujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnl_pengesahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_pemberitahuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_cancel)
                    .addComponent(btn_simpan))
                .addGap(19, 19, 19))
            .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(containerLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnl_pendirian, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(697, Short.MAX_VALUE)))
        );

        add(container);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        ji = new JDialog_Izin(null, true, _id);
        ji.addActionListenerTambahIzin(new aksiButtonMenuTambahIzin());
        ji.setVisible(true);
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        try {
            int selectedRow = Tabel_izin.convertRowIndexToModel(Tabel_izin.getSelectedRow());
            if (selectedRow > -1) {
                JOptionPane.showMessageDialog(this, ti.hpsIzin(selectedRow));
            }
        } catch (SQLException | HeadlessException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Pilih data table");
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        SimpanData();
    }//GEN-LAST:event_btn_simpanActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Date_Pemberitahuan;
    private com.toedter.calendar.JDateChooser Date_akta_berdiri;
    private com.toedter.calendar.JDateChooser Date_akta_perubahan1;
    private com.toedter.calendar.JDateChooser Date_akta_perubahan2;
    private com.toedter.calendar.JDateChooser Date_laporan;
    private com.toedter.calendar.JDateChooser Date_pengesahan;
    private com.toedter.calendar.JDateChooser Date_persetujuan;
    private javax.swing.JTable Tabel_izin;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JPanel container;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnl_akta_perubahan;
    private javax.swing.JPanel pnl_laporan;
    private javax.swing.JPanel pnl_pemberitahuan;
    private javax.swing.JPanel pnl_pendirian;
    private javax.swing.JPanel pnl_pengesahan;
    private javax.swing.JPanel pnl_persetujuan;
    private javax.swing.JTextArea txt_alamat;
    private javax.swing.JTextField txt_noBerdiri;
    private javax.swing.JTextField txt_noLaporan;
    private javax.swing.JTextField txt_noPemberitahuan;
    private javax.swing.JTextField txt_noPengesahan;
    private javax.swing.JTextField txt_noPersetujuan;
    private javax.swing.JTextField txt_noPerubahan1;
    private javax.swing.JTextField txt_noPerubahan2;
    private javax.swing.JTextField txt_notaris1;
    private javax.swing.JTextField txt_notaris2;
    private javax.swing.JTextField txt_notlp;
    // End of variables declaration//GEN-END:variables

    private void cekPanel(String jp, boolean b) {
        if (jp != null) {
            if (jp.equalsIgnoreCase(PERUSAHAAN.UL) || jp.equalsIgnoreCase(PERUSAHAAN.CV)) {
                pnl_akta_perubahan.setVisible(false);
                pnl_laporan.setVisible(false);
                pnl_pemberitahuan.setVisible(false);
                pnl_pengesahan.setVisible(false);
                pnl_persetujuan.setVisible(false);
            } else if (jp.equalsIgnoreCase(PERUSAHAAN.KOPERASI)) {
                pnl_laporan.setVisible(false);
                pnl_pemberitahuan.setVisible(false);
                pnl_pengesahan.setVisible(false);
                pnl_persetujuan.setBorder(
                        new TitledBorder(null, "Persetujuan Menteri Koperasi dan UKM Atas Akta Perubahan Anggaran Dasar",
                        TitledBorder.LEFT, TitledBorder.LEFT, fontBorder));
            } else if (jp.equalsIgnoreCase(PERUSAHAAN.PT)) {
                pnl_akta_perubahan.setVisible(true);
                pnl_laporan.setVisible(true);
                pnl_pemberitahuan.setVisible(true);
                pnl_pengesahan.setVisible(true);
                pnl_persetujuan.setVisible(true);
                pnl_persetujuan.setBorder(new TitledBorder(null, "Persetujuan Menteri Hukum dan HAM Atas Akta Perubahan Anggaran Dasar",
                        TitledBorder.LEFT, TitledBorder.LEFT, fontBorder));
            } else if (jp.equalsIgnoreCase(PERUSAHAAN.PO)) {
                pnl_pendirian.setVisible(false);
                pnl_akta_perubahan.setVisible(false);
                pnl_laporan.setVisible(false);
                pnl_pemberitahuan.setVisible(false);
                pnl_pengesahan.setVisible(false);
                pnl_persetujuan.setVisible(false);
            }
        }
    }

    private void setDocument() {
        txt_noBerdiri.setDocument(new txtNumber_validator());
        txt_noPersetujuan.setDocument(new txtNumber_validator());
        txt_noPerubahan1.setDocument(new txtNumber_validator());
        txt_noPerubahan2.setDocument(new txtNumber_validator());
    }

    private void setDateFormat() {
        Date_akta_berdiri.setDateFormatString(dateFormat);
        Date_akta_perubahan1.setDateFormatString(dateFormat);
        Date_akta_perubahan2.setDateFormatString(dateFormat);
        Date_persetujuan.setDateFormatString(dateFormat);
        Date_Pemberitahuan.setDateFormatString(dateFormat);
        Date_laporan.setDateFormatString(dateFormat);
        Date_pengesahan.setDateFormatString(dateFormat);
    }

    private void clear() {
        txt_noBerdiri.setText("");
        Date_akta_berdiri.setDate(null);
        txt_notaris1.setText("");
        txt_alamat.setText("");
        txt_notlp.setText("");
        txt_noPerubahan1.setText("");
        Date_akta_perubahan1.setDate(null);
        txt_notaris2.setText("");
        txt_noPerubahan2.setText("");
        Date_akta_perubahan2.setDate(null);
        txt_noPersetujuan.setText("");
        Date_persetujuan.setDate(null);
        txt_noPengesahan.setText("");
        Date_pengesahan.setDate(null);
        txt_noLaporan.setText("");
        Date_laporan.setDate(null);
        txt_noPemberitahuan.setText("");
        Date_Pemberitahuan.setDate(null);
    }

    class aksiButtonMenuTambahIzin implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            try {
                JOptionPane.showMessageDialog(null, ti.addIzin(ji.getIzin()));
                ji.clear();
            } catch (SQLException ex) {
                Logger.getLogger(Panel_Legalitas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}
