/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.disperindag.panel;

import com.disperindag.dao.daoKabupaten;
import com.disperindag.dao.daoKecamatan;
import com.disperindag.dao.daoKelurahan;
import com.disperindag.dao.daoPropinsi;
import com.disperindag.model.kabupaten;
import com.disperindag.model.kecamatan;
import com.disperindag.model.kelurahan;
import com.disperindag.model.propinsi;
import com.disperindag.widget.HintTextField;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author oscar
 */
public class panel_wilayah extends javax.swing.JPanel {

    List<propinsi> lp = new ArrayList<>();
    List<kabupaten> lkab = new ArrayList<>();
    List<kecamatan> lkec = new ArrayList<>();
    List<kelurahan> lkel = new ArrayList<>();
    
    DefaultListModel lmProp = new DefaultListModel();
    DefaultListModel lmKab = new DefaultListModel();
    DefaultListModel lmKec = new DefaultListModel();
    DefaultListModel lmKel = new DefaultListModel();
    
    private int id_prop, id_kab, id_kec;
    private String id_kel;
    
    /**
     * Creates new form panel_wilayah
     */
    public panel_wilayah() {
        initComponents();
        initProp();
    }
    
    private void initProp(){
        lmProp.removeAllElements();
        lp = new daoPropinsi().getPropinsi();
        for (propinsi p : lp) {
            lmProp.addElement(p.getNama_prop());
        }
        jList_prop.setModel(lmProp);
    }
    
    private void initKab(List<kabupaten> lk){
        lmKab.removeAllElements();
        for (kabupaten k : lk) {
            lmKab.addElement(k.getNama_kabupaten());
        }
        jList_kab.setModel(lmKab);
    }
    
    private void initKec(List<kecamatan> lk){
        lmKec.removeAllElements();
        for (kecamatan k : lk) {
            lmKec.addElement(k.getNama_kecamatan());
        }
        jList_kec.setModel(lmKec);
    }
    
    private void initKel(List<kelurahan> lk){
        lmKel.removeAllElements();
        for (kelurahan k : lk) {
            lmKel.addElement(k.getNama_kelurahan());
        }
        jList_kel.setModel(lmKel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel_prop = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_prop = new javax.swing.JList();
        txt_kodeProp = new HintTextField("KODE PROPINSI");
        txt_namaProp = new HintTextField("NAMA PROPINSI");
        btn_tambaProp = new javax.swing.JButton();
        btn_hapusProp = new javax.swing.JButton();
        panel_kab = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList_kab = new javax.swing.JList();
        txt_kodeKab = new HintTextField("KODE KABUPATEN");
        txt_namaKab = new HintTextField("NAMA KABUPATEN");
        btn_tambahKab = new javax.swing.JButton();
        btn_hapusKab = new javax.swing.JButton();
        txt_kodeArea = new HintTextField("KODE AREA");
        panel_kec = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList_kec = new javax.swing.JList();
        txt_kodeKec = new HintTextField("KODE KECAMATAN");
        txt_namaKec = new HintTextField("NAMA KECAMATAN");
        btn_tambah_kec = new javax.swing.JButton();
        btn_hapusKec = new javax.swing.JButton();
        panel_kel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList_kel = new javax.swing.JList();
        txt_kodeKel = new HintTextField("KODE KELURAHAN");
        txt_namaKel = new HintTextField("NAMA KELURAHAN");
        btn_tambahKel = new javax.swing.JButton();
        btn_hapusKel = new javax.swing.JButton();
        txt_KodePos = new HintTextField("KODE POS");
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        panel_prop.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Propinsi", 2, 0, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jList_prop.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList_prop.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_propValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList_prop);

        txt_kodeProp.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        btn_tambaProp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/disperindag/img/list_add.png"))); // NOI18N
        btn_tambaProp.setText("Tambah");
        btn_tambaProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambaPropActionPerformed(evt);
            }
        });

        btn_hapusProp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/disperindag/img/list_remove.png"))); // NOI18N
        btn_hapusProp.setText("Hapus");
        btn_hapusProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusPropActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_propLayout = new javax.swing.GroupLayout(panel_prop);
        panel_prop.setLayout(panel_propLayout);
        panel_propLayout.setHorizontalGroup(
            panel_propLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(txt_kodeProp)
            .addComponent(txt_namaProp)
            .addComponent(btn_tambaProp, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
            .addComponent(btn_hapusProp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_propLayout.setVerticalGroup(
            panel_propLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_propLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_kodeProp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_namaProp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_tambaProp)
                .addGap(7, 7, 7)
                .addComponent(btn_hapusProp))
        );

        panel_kab.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kabupaten", 2, 0, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jList_kab.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList_kab.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_kabValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jList_kab);

        btn_tambahKab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/disperindag/img/list_add.png"))); // NOI18N
        btn_tambahKab.setText("Tambah");
        btn_tambahKab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahKabActionPerformed(evt);
            }
        });

        btn_hapusKab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/disperindag/img/list_remove.png"))); // NOI18N
        btn_hapusKab.setText("Hapus");
        btn_hapusKab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusKabActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_kabLayout = new javax.swing.GroupLayout(panel_kab);
        panel_kab.setLayout(panel_kabLayout);
        panel_kabLayout.setHorizontalGroup(
            panel_kabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(txt_kodeKab)
            .addComponent(txt_namaKab)
            .addComponent(btn_tambahKab, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
            .addComponent(btn_hapusKab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txt_kodeArea)
        );
        panel_kabLayout.setVerticalGroup(
            panel_kabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_kabLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_kodeKab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(txt_namaKab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_kodeArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_tambahKab)
                .addGap(11, 11, 11)
                .addComponent(btn_hapusKab))
        );

        panel_kec.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kecamatan", 2, 0, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jList_kec.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList_kec.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_kecValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jList_kec);

        btn_tambah_kec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/disperindag/img/list_add.png"))); // NOI18N
        btn_tambah_kec.setText("Tambah");
        btn_tambah_kec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah_kecActionPerformed(evt);
            }
        });

        btn_hapusKec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/disperindag/img/list_remove.png"))); // NOI18N
        btn_hapusKec.setText("Hapus");
        btn_hapusKec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusKecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_kecLayout = new javax.swing.GroupLayout(panel_kec);
        panel_kec.setLayout(panel_kecLayout);
        panel_kecLayout.setHorizontalGroup(
            panel_kecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(txt_kodeKec)
            .addComponent(txt_namaKec)
            .addComponent(btn_hapusKec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_tambah_kec, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
        );
        panel_kecLayout.setVerticalGroup(
            panel_kecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_kecLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_kodeKec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_namaKec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_tambah_kec)
                .addGap(12, 12, 12)
                .addComponent(btn_hapusKec))
        );

        panel_kel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Keluarahan", 2, 0, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jList_kel.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList_kel.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_kelValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(jList_kel);

        btn_tambahKel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/disperindag/img/list_add.png"))); // NOI18N
        btn_tambahKel.setText("Tambah");
        btn_tambahKel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahKelActionPerformed(evt);
            }
        });

        btn_hapusKel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/disperindag/img/list_remove.png"))); // NOI18N
        btn_hapusKel.setText("Hapus");
        btn_hapusKel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusKelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_kelLayout = new javax.swing.GroupLayout(panel_kel);
        panel_kel.setLayout(panel_kelLayout);
        panel_kelLayout.setHorizontalGroup(
            panel_kelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(txt_kodeKel)
            .addComponent(txt_namaKel)
            .addComponent(btn_tambahKel, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
            .addComponent(btn_hapusKel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txt_KodePos)
        );
        panel_kelLayout.setVerticalGroup(
            panel_kelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_kelLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_kodeKel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_namaKel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_KodePos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_tambahKel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_hapusKel)
                .addGap(4, 4, 4))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DAFTAR WILAYAH");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panel_prop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(panel_kab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(panel_kec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(panel_kel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 851, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_kel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_kec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_kab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(panel_prop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void jList_propValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_propValueChanged
        // TODO add your handling code here:
        try{
            if(jList_prop.getSelectedIndex() > -1){
                id_prop = lp.get( (jList_prop.getSelectedIndex())).getId_prop();
                lkab = new daoKabupaten().getKabupatenByid(id_prop);
                initKab(lkab);
            }
            else {
                lmKab.removeAllElements();
                lmKec.removeAllElements();
                lmKel.removeAllElements();
            }
        }catch(Exception e){ e.printStackTrace();};
    }//GEN-LAST:event_jList_propValueChanged

    private void btn_tambaPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambaPropActionPerformed
        // TODO add your handling code here:
        propinsi p = null;
        try {
            p = new propinsi();
            p.setId_prop(Integer.parseInt(txt_kodeProp.getText()) );
            p.setNama_prop(txt_namaProp.getText());
            if(new daoPropinsi().addPropinsi(p) == true){
                lp.add(p);
                lmProp.addElement(p.getNama_prop());
                clear();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_tambaPropActionPerformed

    private void btn_hapusPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusPropActionPerformed
        try {
            if(new daoPropinsi().deleteProp(id_prop) == true){
                lp.remove(jList_prop.getSelectedIndex());
                lmProp.removeElementAt(jList_prop.getSelectedIndex());
            }
        } catch (SQLException ex) {
            Logger.getLogger(panel_wilayah.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_hapusPropActionPerformed

    private void jList_kabValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_kabValueChanged
        // TODO add your handling code here:
        try{
            if(jList_kab.getSelectedIndex() > -1){
                id_kab = lkab.get( (jList_kab.getSelectedIndex())).getKode_kab();
                lkec = new daoKecamatan().getKecamatanByid(id_kab);
                initKec(lkec);
            }else {
                lmKec.removeAllElements();
                lmKel.removeAllElements();
            }
        }catch(Exception e){e.printStackTrace();};
    }//GEN-LAST:event_jList_kabValueChanged

    private void btn_tambahKabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahKabActionPerformed
        // TODO add your handling code here:
        kabupaten k = null;
        try {
            k = new kabupaten();
            k.setKode_prop(id_prop);
            k.setKode_kab(Integer.parseInt( txt_kodeKab.getText()) );
            k.setNama_kabupaten(txt_namaKab.getText());
            k.setKode_area(Integer.parseInt(txt_kodeArea.getText()));
            if(new daoKabupaten().addKabupaten(k) == true){
                lkab.add(k);
                lmKab.addElement(k.getNama_kabupaten());
                clear();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_tambahKabActionPerformed

    private void btn_hapusKabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusKabActionPerformed
        try {
            // TODO add your handling code here:
            if(new daoKabupaten().deleteKabupaten(id_kab)){
                lkab.remove(jList_kab.getSelectedIndex());
                lmKab.removeElementAt(jList_kab.getSelectedIndex());
            }
        } catch (SQLException ex) {
            Logger.getLogger(panel_wilayah.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_hapusKabActionPerformed

    private void jList_kecValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_kecValueChanged
        // TODO add your handling code here:
        try{
            if(jList_kec.getSelectedIndex() > -1){
                id_kec = lkec.get( (jList_kec.getSelectedIndex())).getKode_kec();
                lkel = new daoKelurahan().getKelurahanByid(id_kec);
                initKel(lkel);
            }else {
                lmKel.removeAllElements();
            }
        }catch(Exception e){e.printStackTrace();};
    }//GEN-LAST:event_jList_kecValueChanged

    private void btn_tambah_kecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah_kecActionPerformed
        // TODO add your handling code here:
        kecamatan k = null;
        try {
            k = new kecamatan();
            k.setKode_kec(Integer.parseInt(txt_kodeKec.getText()));
            k.setKode_kab(id_kab);
            k.setNama_kecamatan(txt_namaKec.getText());
            if(new daoKecamatan().addKecamatan(k) == true){
                lkec.add(k);
                lmKec.addElement(k.getNama_kecamatan());
                clear();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_tambah_kecActionPerformed

    private void btn_hapusKecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusKecActionPerformed
        try {
            // TODO add your handling code here:
            if(new daoKecamatan().deleteKec(id_kec)){
                lkec.remove(jList_kec.getSelectedIndex());
                lmKec.removeElementAt(jList_kec.getSelectedIndex());
            }
        } catch (SQLException ex) {
            Logger.getLogger(panel_wilayah.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_hapusKecActionPerformed

    private void btn_tambahKelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahKelActionPerformed
        // TODO add your handling code here:
        kelurahan k = null;
        try {
            k = new kelurahan();
            k.setId_kel(txt_kodeKel.getText());
            k.setNama_kelurahan(txt_namaKel.getText());
            k.setId_kec(id_kec);
            k.setKodepos(Integer.parseInt(txt_KodePos.getText()));
            if(new daoKelurahan().addKelurahan(k) == true){
                lkel.add(k);
                lmKel.addElement(k.getNama_kelurahan());
                clear();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_tambahKelActionPerformed

    private void btn_hapusKelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusKelActionPerformed
        try {
            if(new daoKelurahan().deleteKel(id_kel)){
                lkel.remove(jList_kel.getSelectedIndex());
                lmKel.removeElementAt(jList_kel.getSelectedIndex());
            }
        } catch (SQLException ex) {
            Logger.getLogger(panel_wilayah.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_hapusKelActionPerformed

    private void jList_kelValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_kelValueChanged
        // TODO add your handling code here:
        try {
            if(jList_kel.getSelectedIndex() > -1){
                id_kel = lkel.get( (jList_kel.getSelectedIndex())).getId_kel();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jList_kelValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hapusKab;
    private javax.swing.JButton btn_hapusKec;
    private javax.swing.JButton btn_hapusKel;
    private javax.swing.JButton btn_hapusProp;
    private javax.swing.JButton btn_tambaProp;
    private javax.swing.JButton btn_tambahKab;
    private javax.swing.JButton btn_tambahKel;
    private javax.swing.JButton btn_tambah_kec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList_kab;
    private javax.swing.JList jList_kec;
    private javax.swing.JList jList_kel;
    private javax.swing.JList jList_prop;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel panel_kab;
    private javax.swing.JPanel panel_kec;
    private javax.swing.JPanel panel_kel;
    private javax.swing.JPanel panel_prop;
    private javax.swing.JTextField txt_KodePos;
    private javax.swing.JTextField txt_kodeArea;
    private javax.swing.JTextField txt_kodeKab;
    private javax.swing.JTextField txt_kodeKec;
    private javax.swing.JTextField txt_kodeKel;
    private javax.swing.JTextField txt_kodeProp;
    private javax.swing.JTextField txt_namaKab;
    private javax.swing.JTextField txt_namaKec;
    private javax.swing.JTextField txt_namaKel;
    private javax.swing.JTextField txt_namaProp;
    // End of variables declaration//GEN-END:variables
    
    private void clear(){
        txt_kodeProp.setText("");
        txt_namaProp.setText("");
        txt_kodeKab.setText("");
        txt_namaKab.setText("");
        txt_kodeKec.setText("");
        txt_namaKec.setText("");
        txt_kodeKel.setText("");
        txt_namaKel.setText("");
        txt_kodeArea.setText("");
    }
}
