/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.disperindag.panel;

import com.disperindag.Util.txtNumber_validator;
import com.disperindag.dao.daoData_pemilik;
import com.disperindag.dao.daoKabupaten;
import com.disperindag.dao.daoKecamatan;
import com.disperindag.dao.daoKelurahan;
import com.disperindag.dao.daoPropinsi;
import com.disperindag.model.Data_pemilik;
import com.disperindag.model.kabupaten;
import com.disperindag.model.kecamatan;
import com.disperindag.model.kelurahan;
import com.disperindag.model.propinsi;
import java.sql.Connection;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author TOSHIBA
 */
public class Panel_Pemilik extends javax.swing.JPanel {

    private List<propinsi> lp = new daoPropinsi().getPropinsi();
    private List<kabupaten> lkab = null;
    private List<kecamatan> lkec = null;
    private List<kelurahan> lkel = null;
    private Connection con = null;
    private daoData_pemilik dp = null;
    private int _id;
    private String namaProp, namaKab, namaKec, namaKel;

    /**
     * Creates new form Panel_Pemilik
     */
    public Panel_Pemilik(Connection con) {
        initComponents();
        this.con = con;
        dp = new daoData_pemilik(con);
        init_combo_propinsi();
//        setDocument();
        clear();
    }

    public void setId(int id) {
        this._id = id;
    }

    private void init_combo_propinsi() {
        combo_prop.removeAllItems();
        combo_prop.addItem("- Pilih -");
        for (propinsi prop : lp) {
            combo_prop.addItem(prop.getNama_prop());
        }
    }

    private void init_combo_kabupaten(List<kabupaten> kab) {
        combo_kab.removeAllItems();
        combo_kab.addItem("- Pilih -");
        for (kabupaten k : kab) {
            combo_kab.addItem(k.getNama_kabupaten());
        }
    }

    private void init_combo_kecamatan(List<kecamatan> kec) {
        combo_kec.removeAllItems();
        combo_kec.addItem("- Pilih -");
        for (kecamatan k : kec) {
            combo_kec.addItem(k.getNama_kecamatan());
        }
    }

    private void init_combo_kelurahan(List<kelurahan> kel) {
        combo_kel.removeAllItems();
        combo_kel.addItem("- Pilih -");
        for (kelurahan k : kel) {
            combo_kel.addItem(k.getNama_kelurahan());
        }
    }

    public void setPemilik(Data_pemilik p) {
        try {
            txt_namaPengurus.setText(p.getNama_pemilik());
            txt_tempatLahir.setText(p.getTempat_lahir());
            date_tglLahir.setDate(p.getTanggal_lahir());
            txt_alamat.setText(p.getAlamat_rumah());
            combo_prop.setSelectedItem(p.getNama_prop());
            combo_kab.setSelectedItem(p.getNama_kab());
            combo_kec.setSelectedItem(p.getNama_kec());
            combo_kel.setSelectedItem(p.getNama_kel());
            txt_noTlp.setText(p.getNo_tlp());
            txt_ktp.setText(p.getNo_ktp());
            txt_wn.setText(p.getKewarganegaraan());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_namaPengurus = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_tempatLahir = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_alamat = new javax.swing.JTextArea();
        combo_kel = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        combo_kec = new javax.swing.JComboBox();
        combo_kab = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        combo_prop = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_noTlp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_ktp = new javax.swing.JTextField();
        txt_wn = new javax.swing.JTextField();
        date_tglLahir = new com.toedter.calendar.JDateChooser();
        btn_simpan = new com.disperindag.widget.Button();
        btn_clear = new com.disperindag.widget.Button();

        jLabel1.setText("Nama Penanggung jawab / direktur");

        jLabel2.setText("Tempat Lahir");

        jLabel4.setText("Tanggal Lahir");

        jLabel3.setText("Alamat rumah");

        txt_alamat.setColumns(20);
        txt_alamat.setRows(3);
        jScrollPane1.setViewportView(txt_alamat);

        combo_kel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_kelItemStateChanged(evt);
            }
        });

        jLabel8.setText("Kelurahan");

        combo_kec.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_kecItemStateChanged(evt);
            }
        });

        combo_kab.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_kabItemStateChanged(evt);
            }
        });

        jLabel7.setText("Kecamatan");

        combo_prop.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_propItemStateChanged(evt);
            }
        });

        jLabel6.setText("Kab/Kota/Kodya");

        jLabel5.setText("Propinsi");

        jLabel9.setText("Nomor Tlp/HP");

        jLabel11.setText("Kewarganegaraan");

        jLabel10.setText("Nomor KTP/Paspor");

        date_tglLahir.setDateFormatString("dd - MMM - yyyy");
        date_tglLahir.setMaxSelectableDate(new java.util.Date(253370743309000L));
        date_tglLahir.setMinSelectableDate(new java.util.Date(-5364683891000L));

        btn_simpan.setText("SIMPAN");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_clear.setText("BERSIHKAN");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_wn, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_namaPengurus, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_noTlp, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date_tglLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combo_prop, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_kec, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combo_kab, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_kel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_ktp, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        containerLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel6, jLabel8});

        containerLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {combo_kab, combo_kel});

        containerLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {combo_kec, combo_prop});

        containerLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, txt_ktp, txt_namaPengurus, txt_noTlp, txt_tempatLahir, txt_wn});

        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_namaPengurus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_tempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(date_tglLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_prop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(combo_kab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_kec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(combo_kel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txt_noTlp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ktp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_wn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan)
                    .addComponent(btn_clear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(container);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        try {
            Data_pemilik p = new Data_pemilik();
            p.setId_pemilik(_id);
            p.setNama_pemilik(txt_namaPengurus.getText());
            p.setTempat_lahir(txt_tempatLahir.getText());
            p.setTanggal_lahir(date_tglLahir.getDate());
            p.setAlamat_rumah(txt_alamat.getText());
            p.setNama_prop(namaProp);
            p.setNama_kab(namaKab);
            p.setNama_kec(namaKec);
            p.setNama_kel(namaKel);
            p.setNo_tlp(txt_noTlp.getText());
            p.setNo_ktp(txt_ktp.getText());
            p.setKewarganegaraan(txt_wn.getText());
            
            if (new daoData_pemilik(con).updatePemilik(p) == true) {
                JOptionPane.showMessageDialog(this, "Data tersimpan");
                clear();
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void combo_propItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_propItemStateChanged
        // TODO add your handling code here:
        if (combo_prop.getSelectedIndex() > 0) {
            int kode = lp.get((combo_prop.getSelectedIndex()) - 1).getId_prop();
            lkab = new daoKabupaten().getKabupatenByid(kode);
            init_combo_kabupaten(lkab);
            namaProp = combo_prop.getSelectedItem().toString();
        } else {
            combo_kab.removeAllItems();
            combo_kec.removeAllItems();
            combo_kel.removeAllItems();
        }
    }//GEN-LAST:event_combo_propItemStateChanged

    private void combo_kabItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_kabItemStateChanged
        // TODO add your handling code here:
        if (combo_kab.getSelectedIndex() > 0) {
            int kode = lkab.get((combo_kab.getSelectedIndex()) - 1).getKode_kab();
            lkec = new daoKecamatan().getKecamatanByid(kode);
            init_combo_kecamatan(lkec);
            namaKab = combo_kab.getSelectedItem().toString();
        } else {
            combo_kec.removeAllItems();
            combo_kel.removeAllItems();
        }
    }//GEN-LAST:event_combo_kabItemStateChanged

    private void combo_kecItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_kecItemStateChanged
        // TODO add your handling code here:
        if (combo_kec.getSelectedIndex() > 0) {
            int kode = lkec.get((combo_kec.getSelectedIndex()) - 1).getKode_kec();
            lkel = new daoKelurahan().getKelurahanByid(kode);
            init_combo_kelurahan(lkel);
            namaKec = combo_kec.getSelectedItem().toString();
        } else {
            combo_kel.removeAllItems();
        }
    }//GEN-LAST:event_combo_kecItemStateChanged

    private void combo_kelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_kelItemStateChanged
        // TODO add your handling code here:
        if (combo_kel.getSelectedIndex() > -1) {
            namaKel = combo_kel.getSelectedItem().toString();
        }
    }//GEN-LAST:event_combo_kelItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JComboBox combo_kab;
    private javax.swing.JComboBox combo_kec;
    private javax.swing.JComboBox combo_kel;
    private javax.swing.JComboBox combo_prop;
    private javax.swing.JPanel container;
    private com.toedter.calendar.JDateChooser date_tglLahir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txt_alamat;
    private javax.swing.JTextField txt_ktp;
    private javax.swing.JTextField txt_namaPengurus;
    private javax.swing.JTextField txt_noTlp;
    private javax.swing.JTextField txt_tempatLahir;
    private javax.swing.JTextField txt_wn;
    // End of variables declaration//GEN-END:variables

    private void setDocument() {
        txt_ktp.setDocument(new txtNumber_validator());
        txt_noTlp.setDocument(new txtNumber_validator());
    }

    private void clear() {
        txt_namaPengurus.setText("");
        txt_tempatLahir.setText("");
        date_tglLahir.setDate(null);
        txt_alamat.setText("");
        combo_prop.setSelectedIndex(0);
        txt_noTlp.setText("");
        txt_ktp.setText("");
        txt_wn.setText("");
    }
}
