/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.disperindag.view;

import com.disperindag.sql.PERUSAHAAN;
import java.awt.event.ActionListener;

/**
 *
 * @author oscar
 */
public class Bentuk_Usaha extends javax.swing.JPanel {

    /**
     * Creates new form Bentuk_Usaha
     */
    public Bentuk_Usaha() {
        initComponents();
        btn_koperasi.setText(PERUSAHAAN.KOPERASI);
        btn_bul.setText(PERUSAHAAN.UL);
        btn_pt.setText(PERUSAHAAN.PT);
        btn_cv.setText(PERUSAHAAN.CV);
        btn_po.setText(PERUSAHAAN.PO);
    }
    
    public void addActionListenerKoperasi(ActionListener l) {
        btn_koperasi.addActionListener(l);
    }
    
    public void addActionListenerPT(ActionListener l) {
        btn_pt.addActionListener(l);
    }
    
    public void addActionListenerCV(ActionListener l) {
        btn_cv.addActionListener(l);
    }
    
    public void addActionListenerUsahaLain(ActionListener l) {
        btn_bul.addActionListener(l);
    }
    public void addActionListenerPO(ActionListener l) {
        btn_po.addActionListener(l);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_koperasi = new com.disperindag.widget.BigButton();
        btn_pt = new com.disperindag.widget.BigButton();
        btn_cv = new com.disperindag.widget.BigButton();
        btn_bul = new com.disperindag.widget.BigButton();
        btn_po = new com.disperindag.widget.BigButton();

        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BENTUK PERUSAHAAN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);

        jPanel2.setLayout(new java.awt.GridLayout(3, 2, 2, 2));

        btn_koperasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/disperindag/img/koperasi.png"))); // NOI18N
        btn_koperasi.setText("KOPERASI");
        jPanel2.add(btn_koperasi);

        btn_pt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/disperindag/img/PT.png"))); // NOI18N
        btn_pt.setText("PERSEROAN TERBATAS (PT)");
        jPanel2.add(btn_pt);

        btn_cv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/disperindag/img/CV.png"))); // NOI18N
        btn_cv.setText("PERSEKUTUAN KOMANDITER(CV)");
        jPanel2.add(btn_cv);

        btn_bul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/disperindag/img/Other.png"))); // NOI18N
        btn_bul.setText("BENTUK USAHA LAIN");
        jPanel2.add(btn_bul);

        btn_po.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/disperindag/img/PO.png"))); // NOI18N
        btn_po.setText("bigButton1");
        jPanel2.add(btn_po);

        jPanel1.add(jPanel2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 11, 10);
        add(jPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.disperindag.widget.BigButton btn_bul;
    private com.disperindag.widget.BigButton btn_cv;
    private com.disperindag.widget.BigButton btn_koperasi;
    private com.disperindag.widget.BigButton btn_po;
    private com.disperindag.widget.BigButton btn_pt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
