/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.disperindag.view;

import com.disperindag.PanelReport.Panel_laporan;
import com.disperindag.Util.GetTanggal;
import com.disperindag.dbBackup.BackupDB;
import com.disperindag.dialog.JDialog_AddData;
import com.disperindag.panel.Panel_DATABASE;
import com.disperindag.panel.Panel_Produk;
import com.disperindag.panel.panel_KegUsaha;
import com.disperindag.panel.panel_wilayah;
import com.disperindag.sql.PERUSAHAAN;
import com.disperindag.widget.About;
import java.awt.CardLayout;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Alvin
 */
public class FORM_MENU_DISPERINDAG extends javax.swing.JFrame {
    
    private CardLayout cl = null;
    private Connection con = null;
    private String jenis_PT = "";
    private JDialog_AddData dialog_TambahData = null;
    private About glassPane;
    private BackupDB bd = new BackupDB();
    
    public FORM_MENU_DISPERINDAG(Connection con) {
        this.con = con;
        initComponents();
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/com/disperindag/img/icon.png")).getImage() );
        setLayout();
        initPanelCard();
        setGlassPane(glassPane);
        label_tgl.setText(GetTanggal.showDateNow());
    }
    
    private void setLayout(){
        cl = (CardLayout)card.getLayout();
        this.setExtendedState(Frame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        cl.show(card, "menu_koperasi");
    }
    
    private void WindowClosed(){
        int reply = JOptionPane.showConfirmDialog(this, "Anda Yakin Ingin Keluar ??", 
                "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if(reply == JOptionPane.YES_OPTION){
            this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            System.exit(0);
        }else if(reply == JOptionPane.NO_OPTION){
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StatusBar = new javax.swing.JToolBar();
        label_status = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        label_tgl = new javax.swing.JLabel();
        card = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuTambah_data = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem_wilayah = new javax.swing.JMenuItem();
        jMenuItem_usaha = new javax.swing.JMenuItem();
        jMenuItem_produk = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem_exit = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuSetting_database = new javax.swing.JMenuItem();
        menu_backup = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem_pembuat = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FORM REGISTRASI PERIZINAN KOTA SALATIGA");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        StatusBar.setRollover(true);

        label_status.setText("Status");
        StatusBar.add(label_status);
        StatusBar.add(jProgressBar1);

        label_tgl.setText("jLabel1");
        StatusBar.add(label_tgl);

        getContentPane().add(StatusBar, java.awt.BorderLayout.PAGE_END);

        card.setLayout(new java.awt.CardLayout());
        getContentPane().add(card, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        jMenuTambah_data.setText("Registrasi Perusahaan");
        jMenuTambah_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTambah_dataActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuTambah_data);
        jMenu1.add(jSeparator1);

        jMenuItem_wilayah.setText("Data Wilayah");
        jMenuItem_wilayah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_wilayahActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_wilayah);

        jMenuItem_usaha.setText("Data Kegiatan Usaha");
        jMenuItem_usaha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_usahaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_usaha);

        jMenuItem_produk.setText("Data Produk");
        jMenuItem_produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_produkActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_produk);
        jMenu1.add(jSeparator2);

        jMenuItem_exit.setText("Exit");
        jMenuItem_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_exitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_exit);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Pengaturan");

        jMenuSetting_database.setText("Database");
        jMenuSetting_database.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSetting_databaseActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuSetting_database);

        menu_backup.setText("Backup");
        menu_backup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_backupActionPerformed(evt);
            }
        });
        jMenu3.add(menu_backup);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Tentang");

        jMenuItem_pembuat.setText("Pembuat");
        jMenuItem_pembuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_pembuatActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_pembuat);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuTambah_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTambah_dataActionPerformed
        // TODO add your handling code here:
        cl.show(card, "menu_koperasi");
    }//GEN-LAST:event_jMenuTambah_dataActionPerformed

    private void jMenuItem_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_exitActionPerformed
        // TODO add your handling code here:
        WindowClosed();
    }//GEN-LAST:event_jMenuItem_exitActionPerformed

    private void jMenuItem_wilayahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_wilayahActionPerformed
        // TODO add your handling code here:
        cl.show(card, "menu_wilayah");
    }//GEN-LAST:event_jMenuItem_wilayahActionPerformed

    private void jMenuItem_usahaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_usahaActionPerformed
        // TODO add your handling code here:
        cl.show(card, "menu_kegUsaha");
    }//GEN-LAST:event_jMenuItem_usahaActionPerformed

    private void jMenuItem_produkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_produkActionPerformed
        // TODO add your handling code here:
        cl.show(card, "menu_produk");
    }//GEN-LAST:event_jMenuItem_produkActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        WindowClosed();
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem_pembuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_pembuatActionPerformed
        // TODO add your handling code here:
        glassPane.setShowMessage(true);
    }//GEN-LAST:event_jMenuItem_pembuatActionPerformed

    private void jMenuSetting_databaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSetting_databaseActionPerformed
        // TODO add your handling code here:
        cl.show(card, "menu_database");
    }//GEN-LAST:event_jMenuSetting_databaseActionPerformed

    private void menu_backupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_backupActionPerformed
        
    }//GEN-LAST:event_menu_backupActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar StatusBar;
    private javax.swing.JPanel card;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_exit;
    private javax.swing.JMenuItem jMenuItem_pembuat;
    private javax.swing.JMenuItem jMenuItem_produk;
    private javax.swing.JMenuItem jMenuItem_usaha;
    private javax.swing.JMenuItem jMenuItem_wilayah;
    private javax.swing.JMenuItem jMenuSetting_database;
    private javax.swing.JMenuItem jMenuTambah_data;
    public static javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    public static javax.swing.JLabel label_status;
    private javax.swing.JLabel label_tgl;
    private javax.swing.JMenuItem menu_backup;
    // End of variables declaration//GEN-END:variables
    
    private void initPanelCard(){
        glassPane = new About();
        Bentuk_Usaha         bu = new Bentuk_Usaha();
        Menu_Data            mk = new Menu_Data(con);
        panel_wilayah        pw = new panel_wilayah();
        panel_KegUsaha       pk = new panel_KegUsaha();
        Panel_Produk         pp = new Panel_Produk();
        Panel_laporan        pl = new Panel_laporan();
        Panel_DATABASE       pb = new Panel_DATABASE();
        
        card.add(mk, "menu_koperasi");
        card.add(bu, "menu_input");
        card.add(pw, "menu_wilayah");
        card.add(pk, "menu_kegUsaha");
        card.add(pl, "menu_laporan");
        card.add(pp, "menu_produk");
        card.add(pb, "menu_database");
        
        mk.addActionListenerTambahData(new AksiButton_Menu_TambahData());
        mk.addActionListenerLaporan(new AksiButton_Menu_Laporan());
        bu.addActionListenerKoperasi(new AksiButton_MenuInput_Koperasi());
        bu.addActionListenerPT(new AksiButton_MenuInput_PT());
        bu.addActionListenerCV(new AksiButton_MenuInput_CV());
        bu.addActionListenerUsahaLain(new AksiButton_MenuInput_UsahaLain());
        bu.addActionListenerPO(new AksiButton_MenuInput_PO());
        glassPane.addActionListenerCLOSEABOUT(new AksiButton_Menu_About());
    }
    
    class AksiButton_MenuInput_Koperasi implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e) {
            jenis_PT = PERUSAHAAN.KOPERASI;
            cl.show(card, "menu_koperasi");
            
            dialog_TambahData = new JDialog_AddData(null, true, con, jenis_PT);
            dialog_TambahData.setVisible(true);
        }
    }
    
    class AksiButton_MenuInput_PT implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e) {
            jenis_PT = PERUSAHAAN.PT;
            cl.show(card, "menu_koperasi");
            
            dialog_TambahData = new JDialog_AddData(null, true, con, jenis_PT);
            dialog_TambahData.setVisible(true);
        }
    }
    
    class AksiButton_MenuInput_CV implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e) {
            jenis_PT = PERUSAHAAN.CV;
            cl.show(card, "menu_koperasi");
            
            dialog_TambahData = new JDialog_AddData(null, true, con, jenis_PT);
            dialog_TambahData.setVisible(true);
        }
    }
    
    class AksiButton_MenuInput_UsahaLain implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e) {
            jenis_PT = PERUSAHAAN.UL;
            cl.show(card, "menu_koperasi");
            
            dialog_TambahData = new JDialog_AddData(null, true, con, jenis_PT);
            dialog_TambahData.setVisible(true);
        }
    }
    
    class AksiButton_MenuInput_PO implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e) {
            jenis_PT = PERUSAHAAN.PO;
            cl.show(card, "menu_koperasi");
            
            dialog_TambahData = new JDialog_AddData(null, true, con, jenis_PT);
            dialog_TambahData.setVisible(true);
        }
    }
    
    class AksiButton_Menu_TambahData implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e) {
            cl.show(card, "menu_input");
        }
    }
    
    class AksiButton_Menu_Laporan implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e) {
            cl.show(card, "menu_laporan");
        }
    }
    
    class AksiButton_Menu_About implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e) {
            glassPane.setShowMessage(false);
        }
    }
}
