/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.disperindag.PanelReport;

import com.disperindag.Util.FilterUsahaModel;
import com.disperindag.Util.comboKab_model;
import com.disperindag.dao.daoKegUsaha;
import com.disperindag.dao.daoProduk;
import com.disperindag.model.keg_usaha;
import com.disperindag.model.produk;
import com.disperindag.sql.PERUSAHAAN;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author oscar
 */
public class pnl_ModalKegUsaha extends javax.swing.JPanel {

    private List<keg_usaha> lk = new daoKegUsaha().getAllUsaha();
    private ArrayList<String> aku = new ArrayList<String>();
    /**
     * Creates new form pnl_ModalKegUsaha
     */
    public pnl_ModalKegUsaha() {
        initComponents();
        setComboModel();
        clear();
    }
    
    private void setComboModel(){
        DefaultComboBoxModel bentukUSH = new DefaultComboBoxModel();
        bentukUSH.addElement(PERUSAHAAN.KOPERASI);
        bentukUSH.addElement(PERUSAHAAN.PT);
        bentukUSH.addElement(PERUSAHAAN.CV);
        bentukUSH.addElement(PERUSAHAAN.PO);
        bentukUSH.addElement(PERUSAHAAN.UL);
        
        for(keg_usaha k : lk){
            aku.add(k.getNama_usaha());
        }
        new FilterUsahaModel(aku.toArray(), combo_kegUsaha);
        
        combo_kab.setModel(new comboKab_model());
        combo_bentukUsaha.setModel(bentukUSH);
    }
    
    public void addActionListenerMODALKEGUSAHA (ActionListener l) {
        btn_ok.addActionListener(l);
    }
    
    public String[] getMODALKEGUSAHA(){
        String[] a = null;
        try {
            String kab = combo_kab.getSelectedItem().toString();
            String modalAwal = txt_modalFrom.getValue().toString();
            String modalAkhir = txt_ModalTo.getValue().toString();
            String bentukUsaha = combo_bentukUsaha.getSelectedItem().toString();
            String kegUsaha = combo_kegUsaha.getSelectedItem().toString();
            
            if(!kab.equals("") && !bentukUsaha.equals("") && !kegUsaha.equals("") && 
                    !modalAwal.equals("") && !modalAkhir.equals("")){
                a = new String[5];
                a[0] = kab;
                a[1] = modalAwal;
                a[2] = modalAkhir;
                a[3] = bentukUsaha;
                a[4] = kegUsaha;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        combo_kab = new javax.swing.JComboBox();
        combo_bentukUsaha = new javax.swing.JComboBox();
        btn_ok = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_modalFrom = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_ModalTo = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        combo_kegUsaha = new javax.swing.JComboBox();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("WILAYAH");

        jLabel3.setText("BENTUK USAHA");

        combo_kab.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        combo_bentukUsaha.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/disperindag/img/printer.png"))); // NOI18N
        btn_ok.setText("CETAK");

        jLabel2.setText("MODAL");

        txt_modalFrom.setText("jFormattedTextField1");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("s/d");

        txt_ModalTo.setText("jFormattedTextField2");

        jLabel5.setText("KEGIATAN USAHA");

        combo_kegUsaha.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_modalFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_ModalTo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
                            .addComponent(combo_kab, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combo_bentukUsaha, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(combo_kegUsaha, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_ok)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel5});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txt_ModalTo, txt_modalFrom});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(combo_kab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_modalFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ModalTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(combo_bentukUsaha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(combo_kegUsaha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ok)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ok;
    private javax.swing.JComboBox combo_bentukUsaha;
    private javax.swing.JComboBox combo_kab;
    private javax.swing.JComboBox combo_kegUsaha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField txt_ModalTo;
    private javax.swing.JFormattedTextField txt_modalFrom;
    // End of variables declaration//GEN-END:variables

    public void clear(){
        combo_kab.setSelectedIndex(-1);
        combo_kegUsaha.setSelectedIndex(-1);
        combo_bentukUsaha.setSelectedIndex(-1);
        txt_modalFrom.setValue(new Double(0));
        txt_ModalTo.setValue(new Double(0));
    }
}
